### ISSUE TITLE
内存值采集不准确？

### ISSUE THREAD

**Issue by raizo-coder** [yanbo92/iOS-perf#5]
我用xcode里头看了内存值大概有200多M
但是执行脚本之后值看到 6-7M的内存值打印信息，没看懂，是单位换算的问题吗？ 能不能解答下？
![微信图片_20220125161151](https://user-images.githubusercontent.com/54347262/150937545-d58386d6-2897-40b6-9194-61bd6bab256b.png)

**Comment by yanbo92** [comment]
要转去[tidevice](https://github.com/alibaba/taobao-iphone-device/issues)项目里问了，这个项目没有处理过性能数据，只是做了可视化
